In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import warnings

In [2]:
warnings.filterwarnings('ignore')

In [3]:
data = pd.read_csv("D:\ML&DL\outlier\data\data.csv")

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le = LabelEncoder()

In [6]:
for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = le.fit_transform(data[col])

In [7]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,1,19,9,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,1
1,0,2,41,9,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,1
2,0,1,46,5,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,0
3,0,1,22,9,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,1
4,0,1,22,9,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1

In [8]:
data['class'][data['class'] == 0] = -1

In [9]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,1,19,9,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,1
1,0,2,41,9,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,1
2,0,1,46,5,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,-1
3,0,1,22,9,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,1
4,0,1,22,9,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()
data.iloc[:,:-1] = scaler.fit_transform(data.iloc[:,:-1])

In [12]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,-0.113551,-0.126061,-0.645384,0.753021,-0.009889,-0.039310,-0.00891,-0.091223,-0.006301,-0.091933,...,-0.813985,-0.779157,-0.280673,0.073120,-0.287993,-0.641804,-0.627365,-0.221668,-0.374281,1
1,-0.113551,2.215916,0.768925,0.753021,-0.010032,-0.039310,-0.00891,-0.091223,-0.006301,-0.091933,...,-1.030895,-1.157831,2.764403,2.375620,-0.287993,-0.641804,-0.627365,-0.385140,-0.374281,1
2,-0.113551,-0.126061,1.090360,-0.739924,-0.010093,-0.039310,-0.00891,-0.091223,-0.006301,-0.091933,...,-0.804947,-0.935081,-0.173828,-0.478183,-0.287993,1.603834,1.614454,-0.385140,-0.374281,-1
3,-0.113551,-0.126061,-0.452524,0.753021,-0.009996,0.052473,-0.00891,-0.091223,-0.006301,-0.091933,...,1.264742,1.069663,-0.440940,-0.380894,0.073759,-0.574435,-0.604947,-0.385140,-0.342768,1
4,-0.113551,-0.126061,-0.452524,0.753021,-0.010010,-0.034582,-0.00891,-0.091223,-0.006301,-0.091933,...,1.264742,1.069663,-0.440940,-0.478183,-0.287993,-0.641804,-0.627365,-0.385140,-0.374281,1

In [13]:
data_inlier = data[data['class'] == 1]
data_outlier = data[data['class'] == -1]

In [14]:
data_test = pd.concat([data_inlier[:1500] , data_outlier[:1500]])
data_train = data_inlier[1500: ]

In [15]:
X_train = data_train.drop(columns=['class'])
y_train = data_train['class']

In [16]:
X_test = data_test.drop(columns=['class'])
y_test = data_test['class']

In [17]:
from sklearn.svm import OneClassSVM

In [18]:
model = OneClassSVM(nu= 0.06)
model.fit(X_train)

OneClassSVM(nu=0.06)

In [19]:
from sklearn.metrics import classification_report

In [20]:
y_pred_train = model.predict(X_train)

In [21]:
np.unique(y_pred_train , return_counts=True)

(array([-1,  1], dtype=int64), array([  716, 11233], dtype=int64))

In [22]:
print(classification_report(y_train , y_pred_train))

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00         0
           1       1.00      0.94      0.97     11949

    accuracy                           0.94     11949
   macro avg       0.50      0.47      0.48     11949
weighted avg       1.00      0.94      0.97     11949

In [23]:
y_pred_test = model.predict(X_test)

In [24]:
np.unique(y_pred_test , return_counts=True)

(array([-1,  1], dtype=int64), array([1490, 1510], dtype=int64))

In [25]:
print(classification_report(y_test , y_pred_test))

              precision    recall  f1-score   support

          -1       0.94      0.94      0.94      1500
           1       0.94      0.94      0.94      1500

    accuracy                           0.94      3000
   macro avg       0.94      0.94      0.94      3000
weighted avg       0.94      0.94      0.94      3000