In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv("D:\ML&DL\outlier\data\data.csv")

In [3]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [4]:
data.dtypes

duration                         int64
protocol_type                   object
service                         object
flag                            object
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate                float64
same_srv_rate                  float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                   int64
dst_host_srv_count               int64
dst_host_same_srv_rate         float64
dst_host_diff_srv_rate         float64
dst_host_same_src_port_rate    float64
dst_host_srv_diff_host_rate    float64
dst_host_serror_rate           float64
dst_host_srv_serror_rate       float64
dst_host_rerror_rate           float64
dst_host_srv_rerror_rate       float64
class                           object
dtype: object

In [5]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le = LabelEncoder()

In [8]:
for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = le.fit_transform(data[col])

In [9]:
data.dtypes

duration                         int64
protocol_type                    int32
service                          int32
flag                             int32
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate                float64
same_srv_rate                  float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                   int64
dst_host_srv_count               int64
dst_host_same_srv_rate         float64
dst_host_diff_srv_rate         float64
dst_host_same_src_port_rate    float64
dst_host_srv_diff_host_rate    float64
dst_host_serror_rate           float64
dst_host_srv_serror_rate       float64
dst_host_rerror_rate           float64
dst_host_srv_rerror_rate       float64
class                            int32
dtype: object

MAD

In [10]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,1,19,9,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,1
1,0,2,41,9,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,1
2,0,1,46,5,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,0
3,0,1,22,9,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,1
4,0,1,22,9,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1

In [11]:
data.corr()['class'] > 0.7

duration                       False
protocol_type                  False
service                        False
flag                           False
src_bytes                      False
dst_bytes                      False
land                           False
wrong_fragment                 False
urgent                         False
hot                            False
num_failed_logins              False
logged_in                      False
num_compromised                False
root_shell                     False
su_attempted                   False
num_root                       False
num_file_creations             False
num_shells                     False
num_access_files               False
num_outbound_cmds              False
is_host_login                  False
is_guest_login                 False
count                          False
srv_count                      False
serror_rate                    False
srv_serror_rate                False
rerror_rate                    False
srv_rerror_rate                False
same_srv_rate                   True
diff_srv_rate                  False
srv_diff_host_rate             False
dst_host_count                 False
dst_host_srv_count              True
dst_host_same_srv_rate         False
dst_host_diff_srv_rate         False
dst_host_same_src_port_rate    False
dst_host_srv_diff_host_rate    False
dst_host_serror_rate           False
dst_host_srv_serror_rate       False
dst_host_rerror_rate           False
dst_host_srv_rerror_rate       False
class                           True
Name: class, dtype: bool

In [12]:
def MAD_outlier_detector(data , columns= None , threshold=3):
    if columns == None:
        data_analyzer = data.drop(columns=['class'])
    else:
        data_analyzer = data[columns]

    median = np.median(data_analyzer , axis = 0)
    MAD = np.median(np.abs(data_analyzer - median) , axis=0)
    mi = (0.6745 * (data_analyzer - median)) / MAD

    y_predict_index = set(np.where(np.abs(mi)>threshold)[0])
    y_true_index = set(np.where(data['class'] == 0)[0])

    true_detection = y_predict_index.intersection(y_true_index)
    hads_dorost = len(true_detection) / len(y_true_index)
    hads_nadorost = (len(y_predict_index) - len(true_detection)) / (len(data) - len(y_true_index))

    report = {"ture_guess" : hads_dorost , "false_guess":hads_nadorost}
    return report

In [13]:
MAD_outlier_detector(data , columns=['same_srv_rate' , 'dst_host_srv_count' , 'flag' , 'same_srv_rate'] , threshold= 2.8)

{'ture_guess': 0.8274716852593034, 'false_guess': 0.11696036880065433}

In [14]:
data.corr()[['same_srv_rate' , 'dst_host_srv_count']] > 0.7

                             same_srv_rate  dst_host_srv_count
duration                             False               False
protocol_type                        False               False
service                              False               False
flag                                  True               False
src_bytes                            False               False
dst_bytes                            False               False
land                                 False               False
wrong_fragment                       False               False
urgent                               False               False
hot                                  False               False
num_failed_logins                    False               False
logged_in                            False               False
num_compromised                      False               False
root_shell                           False               False
su_attempted                         False               False
num_root                             False               False
num_file_creations                   False               False
num_shells                           False               False
num_access_files                     False               False
num_outbound_cmds                    False               False
is_host_login                        False               False
is_guest_login                       False               False
count                                False               False
srv_count                            False               False
serror_rate                          False               False
srv_serror_rate                      False               False
rerror_rate                          False               False
srv_rerror_rate                      False               False
same_srv_rate                         True                True
diff_srv_rate                        False               False
srv_diff_host_rate                   False               False
dst_host_count                       False               False
dst_host_srv_count                    True                True
dst_host_same_srv_rate                True                True
dst_host_diff_srv_rate               False               False
dst_host_same_src_port_rate          False               False
dst_host_srv_diff_host_rate          False               False
dst_host_serror_rate                 False               False
dst_host_srv_serror_rate             False               False
dst_host_rerror_rate                 False               False
dst_host_srv_rerror_rate             False               False
class                                 True                True